online_store/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from online_store import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'Project-miami'), namespace='online_store')),
    path('', include(('users.urls', 'Project-miami'), namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('delete_cart_item/<int:pk>', views.delete_cart_item, name='delete_cart_item'),
    path('edit_cart_item/<int:pk>', views.edit_cart_item, name='edit_cart_item'),
    path('product/<int:pk>', views.product_detail, name='product_detail'),
    path('cart/create_order', views.create_order, name='create_order'),
    path('orders/', views.orders, name='orders'),
    path('sale/', views.sale, name='sale'),
    path('contact/', views.contact, name='contact'),
    path('homepage/', views.products_list, name='homepage'),
    path('supy/', views.supy, name='supy'),
    path('pasta/', views.pasta, name='pasta'),
    path('salaty/', views.salaty, name='salaty'),
    path('drink/', views.drink, name='drink'),
    path('sladkoe/', views.sladkoe, name='sladkoe'),
    path('bakaleya/', views.bakaleya, name='bakaleya'),
    path('antipasta/', views.antipasta, name='antipasta'),
    path('combo/', views.combo, name='combo'),
    path('pizza/', views.pizza, name='pizza')
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('profile_detail/', views.profile_detail, name='profile_detail'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from .bulma_mixin import BulmaMixin


class SignUpForm(BulmaMixin, UserCreationForm):
    username = forms.CharField(label='Write your username')
    email = forms.EmailField(label='Write your email')
    password1 = forms.PasswordInput()
    password2 = forms.PasswordInput()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class SignInFrom(BulmaMixin, AuthenticationForm):
    username = forms.CharField(label='Username')
    password = forms.PasswordInput()

    class Meta:
        model = User
        fields = ['username', 'password']


class EditProfileForm(BulmaMixin, forms.ModelForm):
    email = forms.EmailField(label='Имя')
    phone = forms.CharField(label='Номер телефона')
    data_birthday = forms.DateField(label='Data birthday')
    phone2 = forms.CharField(label='Номер телефона')
    pin = forms.CharField(label='Введите четыре цифры (Pin)')

    class Meta:
        model = User
        fields = ['email', 'phone', 'data_birthday', 'phone2', 'pin']


class ChangePasswordForm(BulmaMixin, PasswordChangeForm):
    old_password = forms.PasswordInput()
    new_password1 = forms.PasswordInput()
    new_password2 = forms.PasswordInput()


class Meta:
    model = User
    fields = ['old_password', 'new_password1', 'new_password2']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, update_session_auth_hash
from . import forms


# Create your views here.


def sign_up(request):
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('shop:products')
    form = forms.SignUpForm()
    return render(request, 'sign_up.html', {'form': form})


def sign_in(request):
    if request.method == 'POST':
        form = forms.SignInFrom(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('shop:products')
    form = forms.SignInFrom()
    return render(request, 'sign_in.html', {'form': form})


def sign_out(request):
    logout(request)
    return redirect('users:sign_in')


def edit_profile(request):
    form = forms.EditProfileForm(request.POST, instance=request.user)
    if form.is_valid():
        form.save()
        return redirect('shop:products')
    form = forms.EditProfileForm(instance=request.user)
    return render(request, 'edit_profile.html', {'form': form})


def reset_password(request):
    form = forms.ChangePasswordForm(request.user, request.POST)
    if request.method == 'POST' and form.is_valid():
        user = form.save()
        update_session_auth_hash(request, user)
        return redirect('users:sign_in')
    form = forms.ChangePasswordForm(request.user)
    return render(request, 'reset_password.html', {'form': form})


def profile_detail(request):
    form = forms.EditProfileForm()
    if form.is_valid():
        form.save()
        return redirect('shop:products')
    form = forms.EditProfileForm()
    return render(request, 'profile_detail.html', {'form': form})

users/templates/edit_profile.html
{% extends 'base_layout.html' %}
{% load static %}
{% block auth %}
    <div class="columns is-centered">
        <div class="column is-4">
            <div class="box has-background-info-light">
                <form class="form  has-text-centered" method="post" enctype="multipart/form-data">
                    <h1 class="title is-size-2 has-text-centered">Edit profile</h1>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="button is-primary is-fullwidth">
                        Submit
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/profile_detail.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
    <section class="section is-large">
        <div class="container_nav">
            <h1 class="title has-text-weight-bold is-3 textcolor">Личные данные</h1>
            {% csrf_token %}
            {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}
            <button class="button ">
                Выйти
            </button>
        </div>
    </section>


    {#    <section class="section is-large">#}
    {#        <div class="container">#}
    {#            <div class="column pt-3 "><h1 class="title">Личные данные#}
    {#            </h1></div>#}
    {#            <div class="field column">#}
    {#                <label class="label">Имя</label>#}
    {#                <div class="control">#}
    {#                    <label>#}
    {#                        <input class="input input1" type="text" placeholder="Илья">#}
    {#                    </label>#}
    {#                </div>#}
    {#            </div>#}
    {##}
    {#            <div class="field column">#}
    {#                <label class="label">Номер телефона</label>#}
    {#                <div class="control">#}
    {#                    <label>#}
    {#                        <input class="input input1 phonenumber" type="" placeholder="+998911234567">#}
    {#                    </label>#}
    {#                </div>#}
    {#            </div>#}
    {##}
    {#            <div class="field column">#}
    {#                <label class="label">Data birthday</label>#}
    {#                <div class="control">#}
    {#                    <label>#}
    {#                        <input class="input input1" type="date" placeholder="">#}
    {#                    </label>#}
    {#                </div>#}
    {#            </div>#}
    {##}
    {#            <div class="field column">#}
    {#                <label class="label">Номер телефона</label>#}
    {#                <div class="control">#}
    {#                    <label>#}
    {#                        <input class="input input1 phonenumber" type="" placeholder="+998911234567">#}
    {#                    </label>#}
    {#                </div>#}
    {#            </div>#}
    {##}
    {#            <div class="field column">#}
    {#                <label class="label">Введите четыре цифры (PIN)</label>#}
    {#                <div class="control">#}
    {#                    <label>#}
    {#                        <input class="input input1" type="text" placeholder="1234">#}
    {#                    </label>#}
    {#                </div>#}
    {#                <br><br>#}
    {#                <button class="button is-medium is-light has-text-weight-bold buttonsignout">#}
    {#                Выйти#}
    {#            </button>#}
    {#                <button class="button is-medium is-light has-text-weight-bold buttonsignout ml-5">#}
    {#                Сохранить#}
    {#            </button>#}
    {#            </div>#}
    {#            </div>#}
    {#    </section>#}


{% endblock %}

users/templates/reset_password.html
<!--{% extends 'base_layout.html' %}-->

<!--{% block auth %}-->
<!--    <div class="columns is-centered">-->
<!--        <div class="column is-4">-->
<!--            <div class="box has-background-info-light">-->
<!--                <form class="form  has-text-centered" method="post">-->
<!--                    <h1 class="title is-size-2 has-text-centered">Reset password</h1>-->
<!--                    {% csrf_token %}-->
<!--                    {% for field in form %}-->
<!--                        <div class="field">-->
<!--                            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>-->
<!--                            {{ field }}-->
<!--                        </div>-->
<!--                    {% endfor %}-->
<!--                    <button type="submit" class="button is-primary is-fullwidth">-->
<!--                        Submit-->
<!--                    </button>-->
<!--                </form>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--{% endblock %}-->

users/templates/sign_in.html
{% extends 'base_layout.html' %}

{% block auth %}
    <div class="columns is-centered">
        <div class="column is-4 is-vcentered" style="margin-top: 10%">
            <div class="box has-background-info-light">
                <form class="form  has-text-centered" method="post">
                    <h1 class="title is-size-2 has-text-centered">Sign In</h1>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="button is-primary is-fullwidth">
                        Submit
                    </button>
                    <p class="content mt-3">
                        Don't have an account?
                        <span>
                           <a href="{% url 'users:sign_up' %}">Sign up here</a>
                       </span>
                    </p>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/sign_up.html
{% extends 'base_layout.html' %}

{% block auth %}
    <div class="columns is-centered" style="margin-top: 6%">
        <div class="column is-4">
            <div class="box has-background-info-light">
                <form class="form  has-text-centered" method="post">
                    <h1 class="title is-size-2 has-text-centered">Sign up</h1>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                            {{ field }} `
                        </div>
                    {% endfor %}
                    <button type="submit" class="button is-primary is-fullwidth">
                        Submit
                    </button>
                    <p class="content mt-3">
                        Already have an account?
                        <span>
                           <a href="{% url 'users:sign_in' %}">Sign in here</a>
                       </span>
                    </p>
                </form>
            </div>
        </div>
    </div>
{% endblock %}