online_store/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from online_store import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'Project-miami'), namespace='online_store')),
    path('', include(('users.urls', 'Project-miami'), namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('delete_cart_item/<int:pk>', views.delete_cart_item, name='delete_cart_item'),
    path('edit_cart_item/<int:pk>', views.edit_cart_item, name='edit_cart_item'),
    path('product/<int:pk>', views.product_detail, name='product_detail'),
    path('cart/create_order', views.create_order, name='create_order'),
    path('orders/', views.orders, name='orders'),
    path('sale/', views.sale, name='sale'),
    path('contact/', views.contact, name='contact'),
    path('homepage/', views.products_list, name='homepage'),
    path('supy/', views.supy, name='supy'),
    path('pasta/', views.pasta, name='pasta'),
    path('salaty/', views.salaty, name='salaty'),
    path('drink/', views.drink, name='drink'),
    path('sladkoe/', views.sladkoe, name='sladkoe'),
    path('bakaleya/', views.bakaleya, name='bakaleya'),
    path('antipasta/', views.antipasta, name='antipasta'),
    path('combo/', views.combo, name='combo'),
    path('pizza/', views.pizza, name='pizza')
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('profile_detail/', views.profile_detail, name='profile_detail'),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    description = models.TextField()
    price = models.IntegerField()
    is_new = models.BooleanField(default=False)
    is_discounted = models.BooleanField(default=False)
    category = models.ForeignKey('shop.Category', default=None, on_delete=models.CASCADE)
    brand = models.ForeignKey('shop.Brand', default=None, on_delete=models.CASCADE)
    thumb = models.ImageField(default='default_product.png', null=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'online_store_products'


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'shop_categories'


class Brand(models.Model):
    name = models.CharField(max_length=50)
    icon = models.ImageField(upload_to='brands')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'shop_brands'


class Slide(models.Model):
    image = models.ImageField(default='slide.jpg')


class CartItem(models.Model):
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return self.product.title

    def total_price(self):
        return self.product.price * self.quantity


# dobavit v pizza
class Order(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    total_price = models.IntegerField()
    customer = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return 'Order # %s' % (str(self.id))


class OrderProduct(models.Model):
    order = models.ForeignKey('shop.Order', on_delete=models.CASCADE, related_name='order_products')
    product = models.ForeignKey('shop.Product', on_delete=models.CASCADE)
    amount = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return '%s x%s - %s' % (self.product, self.amount, self.order.customer.username)

#
# RATE_CHOICES = [
#     (1, '1 - Trash'),
#     (2, '2 - Bad'),
#     (3, '3 - Ok'),
#     (4, '4 - Good'),
#     (5, '5 - Perfect'),
# ]


# class Review(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     date = models.DateTimeField(auto_now_add=True)
#     text = models.TextField(max_length=3000, blank=True)
#     rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES, null=True)
#
#     def __str__(self):
#         return self.user.username

shop/forms.py
from django import forms
from .models import Order
from .bulma_mixin import BulmaMixin


# dobavit v pizza
class OrderForm(forms.Form):
    name = forms.CharField(label='Write your name')
    phone = forms.CharField(label='Write your phone')
    address = forms.CharField(label='Write your address')
    time_delivery = forms.CharField(label='Faster')

    class Meta:
        model = Order
        fields = ['name', 'phone', 'address', 'time_delivery']

# class RateForm(forms.ModelForm):
#     text = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea'}), label='Leave your review here')
#     rate = forms.ChoiceField(choices=RATE_CHOICES, required=True, label='Rate product from 1 to 5')
#
#     class Meta:
#         model = Review
#         fields = ('text', 'rate')

shop/views.py
from django.shortcuts import render, redirect

# from .forms import RateForm
from .models import *
from django.contrib.auth.decorators import login_required
from . import forms
from django.db.models import Q


# Create your views here.
# @login_required(login_url='/users/sign_in')
# def homepage(request):
#     content = Product.objects.all
#     return render(request, 'homepage.html', {'content': content})

def products_list(request):
    product_id = request.GET.get('product')
    category = request.GET.get('category')
    brand = request.GET.get('brand')
    products = Product.objects.all()
    slides = Slide.objects.all()
    if product_id:
        product = Product.objects.get(pk=product_id)
        cart_item = CartItem.objects.filter(product=product)
        if not cart_item:
            cart_item = CartItem.objects.create(customer=request.user, product=product, quantity=1)
            cart_item.save()
            return redirect('shop:homepage')
        for item in cart_item:
            item.quantity += 1
            item.save()
    products = products.filter(category=category) if category else products
    products = products.filter(brand=brand) if brand else products
    return render(request, 'homepage.html', {'products': products, 'slides': slides})


def product_detail(request, pk):
    product = Product.objects.get(pk=pk)
    return render(request, 'sale.html', {'product': product})


def cart(request):
    cart_items = CartItem.objects.filter(customer=request.user)
    total_price = sum([item.total_price() for item in cart_items])
    total_quantity = sum([item.quantity for item in cart_items])

    return render(request, 'cart.html',
                  {'cart_items': cart_items, 'total_quantity': total_quantity, 'total_price': total_price}
                  )


def delete_cart_item(request, pk):
    card_item = CartItem.objects.get(pk=pk).delete()
    return redirect('shop:cart')


def edit_cart_item(request, pk):
    cart_item = CartItem.objects.get(pk=pk)
    action = request.GET.get('action')

    if action == 'take' and cart_item.quantity > 0:
        if cart_item.quantity == 1:
            cart_item.delete()
            return redirect('shop:cart')
        cart_item.quantity -= 1
        cart_item.save()
        return redirect('shop:cart')
    cart_item.quantity += 1
    cart_item.save()
    return redirect('shop:cart')


def create_order(request):
    cart_items = CartItem.objects.filter(customer=request.user)
    total_price = sum([item.total_price() for item in cart_items])
    amount = sum([item.quantity for item in cart_items])
    form = forms.OrderForm(request.POST)

    if request.method == 'POST' and form.is_valid():
        order = Order.objects.create(
            address=request.POST.get('address'),
            phone=request.POST.get('phone'),
            total_price=total_price,
            customer=request.user
        )
        for cart_item in cart_items:
            OrderProduct.objects.create(
                order=order,
                product=cart_item.product,
                amount=cart_item.quantity,
                total=cart_item.total_price(),
            )

        cart_items.delete()
        return redirect('shop:cart')

    form = forms.OrderForm()
    return render(request, 'order_creation_page.html', {
        'cart_items': cart_items,
        'total_price': total_price,
        'amount': amount,
        'form': form})


# def rate_product(request, pk):
#     product = Product.objects.get(pk=pk)
#     reviews = Review.objects.filter(product=product)
#     if request.method == 'POST':
#         form = RateForm(request.POST)
#         if form.is_valid():
#             rating = form.save(commit=False)
#             rating.user = request.user
#             rating.product = product
#             rating.save()
#             return redirect('shop:rate_product', pk=pk)
#     form = RateForm()
#     return render(request, 'homepage.html', {'form': form, 'product': product, 'reviews': reviews})


def orders(request):
    orders_list = Order.objects.all
    return render(request, 'orders.html', {'orders': orders_list})


def sale(request):
    product = Product.objects.all
    return render(request, 'sale.html', {'product': product})


def contact(request):
    contact = Product.objects.all
    return render(request, 'contact.html', {'contact': contact})


def pizza(request, pk):
    category_id = Category.objects.get(pk=pk)
    products = Product.objects.get(category=category_id)
    return render(request, 'pizza.html', {'products': products})


def supy(request):
    product_supy = Product.objects.all
    return render(request, 'supy.html', {'product_supy': product_supy})


def pasta(request, pk):
    category_id = Category.objects.get(pk=pk)
    products = Product.objects.get(category=category_id)
    return render(request, 'pasta.html', {'products': products})


def salaty(request):
    product_salaty = Product.objects.all
    return render(request, 'salaty.html', {'product_salaty': product_salaty})


def drink(request):
    product_drink = Product.objects.all
    return render(request, 'drink.html', {'product_drink': product_drink})


def sladkoe(request):
    product_sladkoe = Product.objects.all
    return render(request, 'sladkoe.html', {'product_sladkoe': product_sladkoe})


def bakaleya(request):
    product_bakaleya = Product.objects.all
    return render(request, 'bakaleya.html', {'product_bakaleya': product_bakaleya})


def antipasta(request):
    product_antipasta = Product.objects.all
    return render(request, 'antipasta.html', {'product_antipasta': product_antipasta})


def combo(request):
    product_combo = Product.objects.all
    return render(request, 'combo.html', {'product_combo': product_combo})

shop/templates/base_layout.html
{% load static %}
{% load categories %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'bulma.css' %}">
    <link rel="stylesheet" href="{% static 'bulma.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/css/bulma-carousel.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
</head>
<body>
<header class="section1 has-background-white is-light  ">
    <div class="container_nav">
        <div class="navbar">
            <figure class="navbar-item">
                <a href="{% url 'online_store:homepage' %}">
                    <img class="imglogosize" src="{% static 'uploads/logo.png' %}" alt="LOGO">
                </a>
            </figure>
            <div class="navbar-end is-vcentered pt-3">
                <button class="button is-rounded is-light has-text-weight-bold">
                    Заказать звонок
                </button>
                <p class="is-size-4 ml-5  has-text-weight-bold textcolor">8 499 391-84-49</p>
            </div>
        </div>
        <div class="navbar-menu is-vcentered">
            <div class="navbar-start is-size-6 is-vcentered ">
                {% categories %}
                <a href="{% url 'online_store:sale' %}" class="level has-text-black mx-3"><span
                        class="has-text-weight-bold">Акции</span></a>
                <a href="{% url 'online_store:combo' %}" class="level has-text-black mx-3"><span
                        class="has-text-weight-bold">Комбо</span></a>
                <a href="{% url 'online_store:contact' %}" class="level has-text-black mx-3"><span
                        class="has-text-weight-bold">Контакты</span></a>
                <a href="{% url 'users:profile_detail' %}" class="level has-text-black mx-3 has-text-weight-semibold">Войти</a>
                <a class="button is-rounded mx-3 color_button btn_color">
                    <div class="text has-text-weight-bold">Kорзина | {{ item.quantity }}</div>
                </a>
            </div>
        </div>
    </div>
</header>
{% block content %}

{% endblock %}


<section class="section">
    <div class="container_nav">
        <footer class="columns">
            <div class="column is-6">
                <figure>
                    <img src="{% static 'uploads/logo.png' %}" alt="">
                </figure>
                <div class="level-item is-justify-content-left navbar-start">
                    <div class="navbar-item has-text-weight-bold pl-0">Калорийность и состав</div>
                    <div class="navbar-item has-text-weight-bold pl-0 ml-6">Правовая информация</div>
                </div>
                <p class="navbar-item has-text-weight-bold pl-0">Мы в соцсетях</p>
                <br><br>
                <div class="columns">
                    <div class="column">
                        <p class="is-dark pl-0">YouTube</p>
                        <p class="is-dark pl-0">Instagram</p>
                    </div>
                    <div class="column is-centern">
                        <p class="is-dark pl-0 ">Facebook</p>
                        <p class="is-dark pl-0 ">ВКонтакте</p>
                    </div>
                    <div class="column">
                        <p>Москва ул. Проспект <br>Вернадского 86В</p>
                    </div>
                </div>
                <br><br>
                <h1 class="is-dark level">YaBao Все праав защищены © 2021</h1>
            </div>
            <div class="column is-7 ">
                <p class="has-text-weight-bold pl-4">Остались вопросы? А мы всегда на связи:</p><br><br>
                <div class="button buttonsize  ml-3"><a href="#"><img class="imgsize"
                                                                      src="{% static 'uploads/viber.svg' %}" alt=""></a>
                </div>
                <div class="button buttonsize ml-3"><a href="#"><img class="imgsize"
                                                                     src="{% static 'uploads/skype.svg' %}" alt=""></a>
                </div>
                <div class="button buttonsize  ml-3"><a href="#"><img class="imgsize"
                                                                      src="{% static 'uploads/message.svg' %}"
                                                                      alt=""></a></div>
                <div class="button buttonsize  ml-3"><a href="#"><img class="imgsize"
                                                                      src="{% static 'uploads/telegram.svg' %}" alt=""></a>
                </div>
                <br><br>
                <div class="button buttonsize  ml-3"><a href="#">
                    <img class="imgsize" src="{% static 'uploads/facebook.svg' %}" alt=""></a></div>
                <div class="button buttonsize  ml-3"><a href="#"><img class="imgsize"
                                                                      src="{% static 'uploads/vk.svg' %}" alt=""></a>
                </div>
                <div class="button buttonradius1 ml-2 has-text-weight-bold">Написать нам</div>
                <br><br><br>
                <p class="is-size-4 has-text-warning has-text-weight-bold ml-4">8 499 391-84-49</p>
                <br>
                <button class="button is-rounded is-light has-text-weight-bold ml-4 ">
                    Заказать звонок
                </button>
            </div>
        </footer>
    </div>
    <img class="imagedown" src="{% static 'uploads/niz-foto.png' %}" alt="">
</section>
<script src="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/js/bulma-carousel.min.js"></script>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
<script>
    bulmaCarousel.attach('#carousel-demo', {
        slidesToScroll: 1,
        slidesToShow: 2,
        infinite: true,
    });
</script>
</body>
</html>

shop/templates/cart.html
{% extends 'second_layout.html' %}
{% load static %}


{% block content %}
    <div class="section is-medium">
        <div class="container_nav2">
            <h1 class="title textcolor">Корзина</h1>
            {#Rectangle#}
            <div class="rectangle is-flex"></div>
            <br><br>
            <div class="columns is-justify-content-center">
                <a href="{% url 'online_store:homepage' %}" class="column">
                    <div class="media is-centered">
                        <figure class="media-left">
                            <p class="image is-64x64">
                                <img src="{{ product.thumb.url }}" alt="pizza"></p>
                        </figure>
                        <div class="media-content">
                            <div class="content">
                                <div class="title has-text-weight-bold">{{ product.title }} <br>
                                    <span class="subtitle ">{{ product.descpription }}</span></div>
                                <span class="textcolor ">{{ product.price }} ₽</span></div>
                            </div>
                        </div>
                </a>
                    </div>

            </div>
        </div>
{% endblock %}

shop/templates/categories.html
<div class="level is-vcentered">
    {% for category in categories %}
        <h1 class="has-text-weight-bold title has-text-warning">{{ products.title }}</h1>
        <div class="level-item mx-3 ">
            <a href="{% url 'online_store:homepage' %}?category={{ category.pk }}"
               class="is-horizontal has-text-black has-text-weight-semibold is-size-6">
                {{ category }}
            </a>
        </div>
    {% endfor %}
</div>

shop/templates/combo.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
    <section class="section is-large container_nav">
        <div>
            <img class="image-down-left-supy" src="{% static 'uploads/img-14.png' %}" alt="">
            <h1 class="is-3 title has-text-weight-bold textcolor">Combo</h1>
            <p class="is-6 subtitle mt-3">В этой категории нет товаров.</p>
            <button class="button color_button is-rounded is-size-5 ">
                <div class=""><a href="{% url 'online_store:combo' %}"
                                 class="has-text-white is-size-6 has-text-weight-bold">Продолжить</a>
                </div>
            </button>
            <img class="image-down-right-supy" src="{% static 'uploads/img1-large.png' %}" alt="">
        </div>

    </section>
{% endblock %}

shop/templates/contact.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
    <section class="section is-medium">
    <div class="container_nav">
        <div class="columns">
            <div class="column pl-6 is-vcentered">
                <iframe class="is-rounded mapsrounded"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2245.011311922709!2d37.65671028365306!3d55.75830570002984!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46b54a8dd1a8f359%3A0x562114fc3541cfb1!2z0JrRg9GA0YHQutCw0Y8!5e0!3m2!1sru!2s!4v1651566100376!5m2!1sru!2s"
                        width="1000" height="350" style="border:0;" allowfullscreen="" loading="lazy"
                        referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
        <p class="is-size-1 textcolor pl-6 has-text-weight-bold ">8 800 333-36-62</p>
        <p class="is-size-1 pl-6 has-text-weight-bold">ул. Проспект Вернадского 86В</p>
        <p class=" pl-6 has-text-weight-bold">Доставка и самовывоз 10:00 — 23:00</p>
        </div>
    </section>

    <img class="imgright1 image" src="{% static 'uploads/img1.png' %}" alt="">

{% endblock %}

shop/templates/homepage.html
{% extends 'base_layout.html' %}
{% load static %}
{% load categories %}

{% block content %}
    <div class="section is-medium">
        {% block slider %}
            <div class="container-slide mb-6">
                <div id="carousel-demo" class="carousel">
                    {% for slide in slides %}
                        <div class="item-1">
                            <img class="slider-img" src="{{ slide.image.url }}" alt="">
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endblock %}
        <div class="imageleft">
            <img src="{% static 'uploads/img-14.png' %}" alt="">
        </div>

        {#  Cards mini  #}
        <div class="container_nav">
            <h1 class="is-size-3 has-text-weight-bold title">Новинки</h1>
            <div class="columns is-justify-content-center">
                <a href="{% url 'online_store:homepage' %}" class="column">
                    <div class="box ">
                        <div class="media is-centered">
                            <figure class="media-left">
                                <p class="image is-64x64">
                                    <img src="{% static 'uploads/small-pizza1.png' %}" alt="pizza"></p>
                            </figure>
                            <div class="media-content">
                                <div class="content">
                                    <div class="subtitle has-text-weight-bold">Карбонара <br> <span
                                            class="has-text-warning ">от 120 ₽</span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>

                <div class="column">
                    <div class="box pl-3">
                        <div class="media ">
                            <figure class="media-left">
                                <p class="image is-64x64">
                                    <img src="{% static 'uploads/small-pizza1.png' %}" alt="pizza"></p>
                            </figure>
                            <div class="media-content">
                                <div class="content">
                                    <div class="subtitle has-text-weight-bold">Карбонара <br> <span
                                            class="has-text-warning ">от 120 ₽</span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="column">
                    <div class="box pl-3">
                        <div class="media ">
                            <figure class="media-left">
                                <p class="image is-64x64">
                                    <img src="{% static 'uploads/small-pizza1.png' %}" alt="pizza"></p>
                            </figure>
                            <div class="media-content">
                                <div class="content">
                                    <div class="subtitle has-text-weight-bold">Карбонара <br> <span
                                            class="has-text-warning ">от 120 ₽</span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="column">
                    <div class="box pl-3">
                        <div class="media ">
                            <figure class="media-left">
                                <p class="image is-64x64">
                                    <img src="{% static 'uploads/small-pizza1.png' %}" alt="pizza"></p>
                            </figure>
                            <div class="media-content">
                                <div class="content">
                                    <div class="subtitle has-text-weight-bold">Карбонара <br> <span
                                            class="has-text-warning ">от 120 ₽</span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br><br>

        {# Card product #}
        <div class="container_nav ">
            <h1 class="has-text-weight-bold title has-text-warning">{{ products.title }}</h1>
            <div class="columns is-multiline p-0">
                {% for product in products %}
                    <div class="column is-3">
                        <img src="{{ product.thumb.url }}" alt="">
                        <h2 class="title has-text-weight-bold">{{ product.title }}</h2>
                        <p class="subtitle is-6 mt-0">{{ product.description }}</p>
                        <div class="columns is-vcentered is-justify-content-space-between">
                            <h1 class="ml-4 is-size-4 has-text-weight-bold">от {{ product.price }} ₽</h1>
                            <a href="{% url 'online_store:homepage'%}"
                               class="button is-rounded is-warning has-text-weight-bold mr-3">В корзину
                            </a>
                        </div>


                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <br>
    <section class="section">
        <div class="container_nav">
            <div class="h3_m has-text-weight-bold">Наши<span class="textcolor"> акции</span></div>
            <div class="tile is-ancestor m-6">
                <div class="tile is-parent">
                    <img src="{% static 'uploads/image-26-big.jpg' %}" alt="">
                </div>
                <div class="tile">
                    <div class="tile is-parent is-vertical">
                        <div class="tile is-child">
                            <img src="{% static 'uploads/small.jpg' %}" alt="">
                        </div>
                        <div class="tile is-child">
                            <img src="{% static 'uploads/small.jpg' %}" alt="">
                        </div>
                    </div>
                    <div class="tile is-parent is-vertical">
                        <div class="tile is-child">
                            <img src="{% static 'uploads/small.jpg' %}" alt="">
                        </div>
                        <div class="tile is-child">
                            <img src="{% static 'uploads/small.jpg' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <img class="image-down-right" src="{% static 'uploads/img1-large.png' %}" alt="">
    </section>

    <section class="section has-background-grey-lighter">
        <div class="container_nav">

            <h1 class="title has-text-centered">Оплата и доставка</h1>
            <div class="columns is-vcentered is-centered is-1">
                <div class="column">
                    <div class="boxrounded">
                        <img class="card-icon is-vcentered" src="{% static 'uploads/image-15.png' %}"
                             alt="">
                        <div class="subtitle is-6 mt-3 has-text-centered">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit
                        </div>
                    </div>
                </div>

                <div class="column">
                    <div class="boxrounded">
                        <img class="card-icon is-vcentered" src="{% static 'uploads/image-15-1.png' %}"
                             alt="">
                        <div class="subtitle is-6 mt-3 has-text-centered">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit
                        </div>
                    </div>
                </div>

                <div class="column">
                    <div class="boxrounded">
                        <img class="card-icon" src="{% static 'uploads/image-15-2.png' %}" alt="">
                        <div class="subtitle is-6 mt-3 has-text-centered">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit
                        </div>
                    </div>
                </div>

                <div class="column">
                    <div class="boxrounded">
                        <img class="card-icon" src="{% static 'uploads/image-15-3.png' %}" alt="">
                        <div class="subtitle is-6 mt-3 has-text-centered">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <div class="mapsrounded2 is-rounded">
                    <iframe class="mapsrounded2 is-vcentered ml-5 mr-5"
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2245.011311922709!2d37.65671028365306!3d55.75830570002984!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46b54a8dd1a8f359%3A0x562114fc3541cfb1!2z0JrRg9GA0YHQutCw0Y8!5e0!3m2!1sru!2s!4v1651566100376!5m2!1sru!2s"
                            width="1290" height="350" style="" allowfullscreen="" loading="lazy"
                            referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

shop/templates/order_creation_page.html
{% extends 'base_layout.html' %}
{% load static %}


{% block content %}

{% endblock %}

shop/templates/products_list.html
{% extends 'base_layout.html' %}
{% load categories %}

{% block content %}

{% endblock %}